### ISSUE TITLE
How to compile it on macOS?

### ISSUE THREAD

**Issue by QinGeneral** [Ericsson/ETCPACK#13]
I want to know how to compile it on macOS? Thanks.

When I use ```gcc etcpack.cpp```  to compile it, I got a error:
```cpp
etcpack.cpp:15573:6: note: use '==' to turn this assignment into an equality comparison
        if(f=fopen(dstfile,"wb"))
            ^
            ==
etcpack.cpp:15885:16: error: variable has incomplete type 'struct _timeb'
        struct _timeb tstruct;
                      ^
etcpack.cpp:15885:9: note: forward declaration of '_timeb'
        struct _timeb tstruct;
               ^
59 warnings and 1 error generated.
```

**Comment by jacobstrom-ericsson** [comment]
Hi @QinGeneral,

I just cloned the repository and tried to compile the code in Xcode on macOS. The lines containing the variables tstart, tstop and tstruct, are only present in order to measure the time to compress and are not strictly necessary for running the code. By commenting out all the lines containing these three variables the program compiles and runs on my Mac.

I hope this is helpful,

-Jacob

**Comment by QinGeneral** [comment]
@jacobstrom-ericsson Thanks, I just try the method mention above, but I still got an error when using `gcc etcpack.cxx`.  Does it must be compiled in Xcode?

The error is:
```
Undefined symbols for architecture x86_64:
  "decompressColor(int, int, int, unsigned char (*) [3], unsigned char (*) [3])", referenced from:
...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by jacobstrom-ericsson** [comment]
Hi @QinGeneral,

I personally use Xcode and have only tried that. I don't know if just running "gcc etcpack.cxx" is the correct way to compile this under gcc -- I would assume you would need to somehow help gcc to find the other files as well, but since I am not using gcc myself, I don't really know. 

In Xcode, this is a way to compile it:

Start Xcode,
Select "Create a new Xcode project"
Select the macOS tab
Select "Command Line Tool"
Press Next
Enter project name, for instance etcpack 
Select C++ as the language
Press Next
Select a directory and press "Create"
Right click on main.cpp and select "Delete" (this was autogenerated by Xcode and is not needed)
Select "Move to trash"
Right click on the project name folder to the left (which previously contained main.cpp)
Select 'Add files to "etcpack"...'
Navigate to the source directory and select all four files etcpack.cxx, image.h, image.cxx and etcdec.cxx, then press Add.
Remove the lines containing the variables tstart, tstop and tstruct if you have not already done so
Compile by selecting Product->Run or pressing the triangle shaped button in the top left
Your program should now build.

**Comment by QinGeneral** [comment]
Hi @jacobstrom-ericsson ,
By following your steps, I build ETCPACK success. Thank you a lot. 💪️💪️💪️
